// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RagChatbot.DAL.Data;

#nullable disable

namespace RagChatbot.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603130354_AddFullNameToUser")]
    partial class AddFullNameToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagChatbot.DAL.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Nguyễn Quản Trị",
                            Password = "123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Trần Thị Hương",
                            Password = "123",
                            Role = "Lecturer",
                            Username = "giangvien"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Lê Văn An",
                            Password = "123",
                            Role = "Student",
                            Username = "sinhvien"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Phạm Quốc Minh",
                            Password = "123",
                            Role = "Lecturer",
                            Username = "gv_minh"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Ngô Thị Lan",
                            Password = "123",
                            Role = "Lecturer",
                            Username = "gv_lan"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Đặng Châu Bảo",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_bao"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Hoàng Minh Tùng",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_tung"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Vũ Thị Linh",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_linh"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Bùi Thanh Khoa",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_khoa"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Trịnh Thị Ngân",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_ngan"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Lý Công Hiếu",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_hieu"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Dương Thị Phương",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_phuong"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Mai Xuân Đức",
                            Password = "123",
                            Role = "Student",
                            Username = "sv_duc"
                        });
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.UserSubject", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("UserSubjects");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.Document", b =>
                {
                    b.HasOne("RagChatbot.DAL.Entities.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.DocumentChunk", b =>
                {
                    b.HasOne("RagChatbot.DAL.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.UserSubject", b =>
                {
                    b.HasOne("RagChatbot.DAL.Entities.Subject", "Subject")
                        .WithMany("UserSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbot.DAL.Entities.User", "User")
                        .WithMany("UserSubjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.Subject", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("UserSubjects");
                });

            modelBuilder.Entity("RagChatbot.DAL.Entities.User", b =>
                {
                    b.Navigation("UserSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
